// This list exports to the puzzles app all of our puzzle files. This combines the puzzles provided by all submodules into a single list.
// This helps compilation function without needing to run cmake on the modules to generate it!
// Note that when a new game is added, it will need to be manually added to this file.

GAME(blackbox)
GAME(bridges)
GAME(cube)
GAME(dominosa)
GAME(fifteen)
GAME(filling)
GAME(flip)
GAME(flood)
GAME(galaxies)
GAME(group) //Experimental puzzle
GAME(guess)
GAME(inertia)
GAME(keen)
GAME(lightup)
GAME(loopy)
GAME(magnets)
GAME(map)
GAME(mines)
GAME(mosaic)
GAME(net)
GAME(netslide)
GAME(palisade)
GAME(pattern)
GAME(pearl)
GAME(pegs)
GAME(range)
GAME(rect)
GAME(samegame)
GAME(seismic)
GAME(signpost)
GAME(singles)
GAME(sixteen)
GAME(slant)
GAME(solo)
GAME(tents)
GAME(towers)
GAME(tracks)
GAME(twiddle)
GAME(undead)
GAME(unequal)
GAME(unruly)
GAME(untangle)

// Lennard Sprong (x-sheep) Puzzles
GAME(abcd)
GAME(ascent)
GAME(boats)
GAME(bricks)
GAME(clusters)
//GAME(crossing)
GAME(mathrax)
GAME(rome)
GAME(salad)
GAME(spokes)
GAME(sticks)
GAME(subsets)

// Steffen Bauer Puzzles
GAME(flow)
GAME(walls)

// Anders Holst
// Currently disabled: These require modifications to the midend
//GAME(alphacrypt)
//GAME(factorcross)
//GAME(identifier)
//GAME(kakuro)
//GAME(supermaze)
